version: '3.8'

services:
  web:
    build: ./src
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    container_name: xsstrange-web
    restart: unless-stopped
    stop_grace_period: 1m
